### ISSUE TITLE
interaction with hyperref-option bookmarks=false

### ISSUE THREAD

**Issue by Ulrich-Diez** [ho-tex/bookmark#2]
The **hyperref**-package can be loaded with the `bookmarks=false`-option for avoiding the creation of bookmarks.  
The package **bookmark** does override that option.

E.g., the following yields a pdf-file with bookmarks:

```
\documentclass{article}
\usepackage[bookmarks=false]{hyperref}
\usepackage{bookmark}
\begin{document}
\section{First section}
Text of first section.
\section{Second section}
Text of second section.
\end{document}
```

Perhaps the package  **bookmark** can be changed to take **hyperref**'s  `bookmarks=false`-option into account?

You might ask the question why to load the **bookmark**-package at all when specifying `bookmarks=false`?

There are document-classes like the KOMA-Script-classes which do automatically load the **bookmark**-package in case the **hyperref**-package is loaded.  
Currently the KOMA-Script-classes do so even if **hyperref** is loaded with `bookmarks=false`.  
I already reported this, see [https://komascript.de/node/2286](https://komascript.de/node/2286) and [https://komascript.de/node/2287](https://komascript.de/node/2287).  
The KOMA-Script-maintainer seems to refuse to take the issue for a bug in the way in which his classes load other packages.

E.g., with the KOMA-Script-class **scrreprt** the following yields the error

`pdfTeX warning (dest): name{chapter.1} has been referenced but does not exist, replaced by a fixed one.`

, while with **memoir** or the standard-class **report** you don't get that error:

```
\documentclass{scrreprt}
%\documentclass{report}
%\documentclass{memoir}
 
\usepackage[bookmarks=false]{hyperref}
 
\begin{document}
 
\begin{NoHyper}
 
\chapter{A chapter}
Text of the chapter.
 
\end{NoHyper}
 
\end{document}
```

The reason is: Unlike **memoir** and **report** the class **scrreprt** does also load the **bookmark**-package. That overrides the `bookmarks=false`-option. Thus with **scrreprt** there are attempts at creating and linking bookmarks although the creation of corresponding destinations/targets/anchors is suppressed by the `NoHyper`-environment.

Currently with KOMA-Script-classes you can do:

```
\documentclass[bookmarkpackage=false]{scrreprt}
%\documentclass{report}
%\documentclass{memoir}
 
\usepackage[bookmarks=false]{hyperref}
 
\begin{document}

\begin{NoHyper}
 
\chapter{A chapter}
Text of the chapter.
 
\end{NoHyper}

\end{document}
```

The not so experienced user might not be aware of this.

But there are scenarios where you wish to switch between **hyperref** creating hyperlinks and bookmarks (e.g. with pdfs for viewing online) and **hyperref** not doing so  (e.g. with pdfs for printing).

Currently my template for this kind of things looks like this:

```
\documentclass[bookmarkpackage=false]{scrreprt}
%\documentclass{report}
%\documentclass{memoir}
 
% In case you wish no hyperlinks and no bookmarks:
  \AtBeginDocument{\NoHyper}
  \usepackage[bookmarks=false]{hyperref}
% In case you wish hyperlinks and bookmarks:
  %\usepackage{hyperref}
 
\begingroup
\makeatletter
\@firstofone{%
  \endgroup
  \ifHy@bookmarks\usepackage{bookmark}\fi
}%
 
\begin{document}
 
\chapter{A chapter}
Bla Bla
 
\end{document}
```

The not so experienced user might not be aware of how to use all these `\makeatletter`-thingies for resolving this.

**Comment by davidcarlisle** [comment]
generating an error isn't good but which way to jump?


It seems like, in bookmarks after

`\RequirePackage{hyperref}[2010/06/18]`

then if \ifHY@bookmarks is false you could make some warning and skip the rest of the package so it does nothing, or you could set the boolean to true and undo the effect of this load time use of the flag in hyperref so that the using the bookmarks package means the bookmark package is enabled.


```
\ifHy@bookmarks
  \Hy@Info{Bookmarks ON}%
  \ifx\@pdfpagemode\@empty
    \def\@pdfpagemode{UseOutlines}%
  \fi
\else
  \let\@bookmarkopenstatus\ltx@gobble
  \Hy@Info{Bookmarks OFF}%
  \Hy@AtEndOfPackage{%
    \global\let\ReadBookmarks\relax
    \global\let\WriteBookmarks\relax
  }%
  \ifx\@pdfpagemode\@empty
    \def\@pdfpagemode{UseNone}%
  \fi
\fi
```

The first is easier  but I'm not sure it is what the user expects in that case.

On the other hand, if we were to incorporate bookmarks into hyperref and make bookmarks a stub package that did nothing, having the bookmarks hyperref option always honoured would be what you want so perhaps that would be best.... @u-fischer  ?

**Comment by u-fischer** [comment]
I would simply suppress the bookmarks  by setting the depth to a negative value:

~~~
\documentclass{scrreprt}
\usepackage{bookmark}
\bookmarksetup{depth=-2}
\begin{document}

\section{First section}
Text of first section.
\section{Second section}
Text of second section.
\end{document}
~~~~


As an alternative you can pass the option `draft` to bookmark. hyperref must then be loaded first, to avoid that it gets the draft option too.

~~~~
\documentclass{scrreprt}
%\documentclass{report}
%\documentclass{memoir}
\usepackage{hyperref}
\PassOptionsToPackage{draft}{bookmark}
\begin{document}

\begin{NoHyper}

\chapter{A chapter}
Text of the chapter.

\end{NoHyper}

\section{First section}
Text of first section.
\section{Second section}\label{a}
Text of second section.

\ref{a} \url{https://www.dante.de}

\end{document}
~~~~

Imho that is rather arkward.

**Comment by u-fischer** [comment]
Btw: The coordination between hyperref and bookmark should be improved, but I don't see a KOMA bug here. The class loads the bookmark package under certain conditions, documents this and offers a option to suppress it. You can easily do 

~~~~
\usepackage[bookmarks=false]{hyperref}
\KOMAoptions{bookmarkpackage=false}
~~~~

and then you have the setup as with memoir.
