### ISSUE TITLE
Using bookmark causes floating point exception in dvipng

### ISSUE THREAD

**Issue by fjwright** [ho-tex/bookmark#5]
When I use the latest TeX Live (from ctan.org) and compile the LaTeX file, dvipng-bug.tex, containing the following 5 lines:

\documentclass{article}
\usepackage{bookmark}
\begin{document}
Some random content.
\end{document}

using “latex dvipng-bug.tex” and then run “dvipng dvipng-bug.dvi”, I get the output:

This is dvipng 1.17 Copyright 2002-2015, 2019 Jan-Ake Larsson
Floating point exception (core dumped)

and no PNG file. I believe that this is caused by a bad interaction between the latest version of the bookmark driver file bkm-dvips.def, namely version 2020-11-06 v1.29, and dvipng. I have tried using dvipng 1.16 and 1.15, and the result is the same. But if I use the previous version of bkm-dvips.def, namely version 2019/12/03 v1.28, dvipng runs correctly. I find similar behaviour on Cygwin and Ubuntu. I have also reported this as a dvipng bug.

(This issue arose from running TeX4ht, which by default can call dvipng many times to generate images of mathematics and other structures that are difficult to translate to HTML.)

**Comment by davidcarlisle** [comment]
Thanks for the file, I can confirm I get same here so we'll see what we can do... Core dump on the face of it suggests an issue in the dvipng but as you say an older def file avoids the issue we should be able to at least narrow down what operation is triggering this.

**Comment by u-fischer** [comment]
dvipgn doesn't like the syntax  PSfile 


~~~
\def\BKM@PSHeaderFile#1{%
  \special{PSfile=#1}%
}
~~~

with `\special{header=#1}` it works.

**Comment by u-fischer** [comment]
The file is added in the shipout/lastpage hook, removing the bookmark code from it avoids the error too (but naturally it is easier to simply remove bookmark ...).

**Comment by davidcarlisle** [comment]
@u-fischer  ah so if we had a dvipng option we could avoid it but simpler (as most people won't force dvipng-specific processing) would be if dvipng coped with the special at least to some extent?

**Comment by u-fischer** [comment]
@davidcarlisle  I saw the discussion already on the tex4ht list and looked a bit at the dvipng documentation.  It seems to support some dvips specials and even some postscript, but it is quite unclear  to which extend and what it is needs.  Imho either dvipng copes with this on its own, or they will have to give a sensible spec if we should add backend support (for bookmark it should be easy, the commands should simply do nothing, but there are perhaps other places which can fail too).

**Comment by jfbu** [comment]
Link to the discussion on dvipng list: https://lists.nongnu.org/archive/html/dvipng/2021-03/msg00003.html

An explicit "dvipng" option could impact Emacs/AUCTeX usage of `dvipng` for its preview mechanism.  Please make sure to alert auctex maintainers if this is done.

**Comment by u-fischer** [comment]
bookmark uses `PSfile` instead of `header` to include the bookmarks to resolve a clash with pgf, see https://github.com/pgf-tikz/pgf/issues/944#issuecomment-723099952.

**Comment by fjwright** [comment]
Thanks to David and Ulrike for investigating this problem. The author of dvipng has agreed to revise it to accept an empty image, which I hope will resolve the problem.
