### ISSUE TITLE
Make chapter bookmarks target to top of pages rather than the positions of chapter titles

### ISSUE THREAD

**Issue by balthild** [ho-tex/bookmark#6]
Hello. Currently, The bookmarks generated from TOC will target to the chapter title. But I want them to target to the top of pages. How could I do that?

I've tried passing `view={XYZ 0 0 null}` option to the package, but it doesn't work. These bookmarks are not added by me directly with `\bookmark` command and I don't know how to pass `view` option to each of them.

**Comment by u-fischer** [comment]
This here is a bug tracker. For general support please go to some general question and answer site. 

https://www.latex-project.org/help/links/#question-and-answer-websites

**Comment by balthild** [comment]
OK, I see.
