### ISSUE TITLE
can't unpack bookmark-frozen.dtx

### ISSUE THREAD

**Issue by kberry** [ho-tex/bookmark#9]
Despite stated instructions for unpacking, `tex bookmark-frozen.dtx` results in
```
This is TeX, Version 3.141592653 (TeX Live 2023) (preloaded format=tex)         
(./bookmark-frozen.dtx                                                          
! Undefined control sequence.                                                   
l.85 \NeedsTeXFormat                                                            
                    {LaTeX2e}           
```
(I suggest distributing .ins files.) Anyway, thanks in advance ...

**Comment by davidcarlisle** [comment]
Hmm the ins you get from `tex bookmark.dtx`  unpacks the whole bundle. Does the doc say that `tex bookmark-frozen.dtx` will work (I couldn't find that just now)

**Comment by davidcarlisle** [comment]
we could anyway include the generated .ins in the ctan bundle, it's probably clearer

**Comment by u-fischer** [comment]
we could add the ins to the github. I find the "everything-in-one" system confusing anyway ;-)

**Comment by u-fischer** [comment]
@kberry  I have uploaded a new version. The bookmark-frozen.dtx is gone (it contained only outdated drivers). I have changed (and simplified) the dtx. It is no longer a selfextracting dtx, but simply a normal dtx and there is an external .ins for the installation.

**Comment by kberry** [comment]
Thanks much. I imported the new bookmark release to TL. No problems :). -k
